repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(api|parser|infra/pal)/
      - id: ruff-format
        files: ^(api|parser|infra/pal)/

  - repo: local
    hooks:
      - id: check-secrets
        name: check-secrets
        entry: scripts/check_secrets.sh
        language: script
        pass_filenames: false
