replicaCount: 1

image:
  repository: hcp-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: hcp.local
      paths:
        - path: /
          pathType: Prefix

env:
  HCP_PROVIDER: onprem
  HCP_ENV: dev
  MINIO_ENDPOINT: http://minio.hcp.svc.cluster.local:9000
  MINIO_BUCKET: hcp-local
  REDIS_URL: redis://redis.hcp.svc.cluster.local:6379/0

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
