replicaCount: 1

image:
  repository: hcp-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: hcp.local
      paths:
        - path: /
          pathType: Prefix

credentialsSecret: hcp-credentials

database:
  host: postgres

env:
  HCP_PROVIDER: onprem
  HCP_ENV: dev

parser:
  enabled: false
  replicaCount: 1
  image:
    repository: hcp-parser
    tag: latest
    pullPolicy: IfNotPresent
  queue: hcp.parse
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
