apiVersion: v2
name: hcp-platform
description: HCP on-premises platform umbrella chart
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: hcp-api
    version: 0.1.0
    repository: "file://../hcp-api"
