global:
  namespace: hcp
  environment: dev

postgresql:
  enabled: true
  fullnameOverride: postgres
  auth:
    username: hcp
    password: hcp
    database: hcp
  primary:
    persistence:
      enabled: true
      size: 8Gi

redis:
  enabled: true
  fullnameOverride: redis
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

minio:
  enabled: true
  fullnameOverride: minio
  mode: standalone
  auth:
    rootUser: hcp
    rootPassword: hcpsecret
  defaultBuckets: hcp-local
  persistence:
    enabled: true
    size: 10Gi

minioInit:
  enabled: true

secrets:
  create: true
  jwtSecret: dev-only-change-in-production
  postgresUser: hcp
  postgresPassword: hcp
  postgresDatabase: hcp
  minioAccessKey: hcp
  minioSecretKey: hcpsecret
  minioBucket: hcp-local
  minioRegion: us-east-1

migrate:
  enabled: true
  backoffLimit: 6

backup:
  enabled: true
  schedule: "0 */6 * * *"
  retentionDays: 7
  persistence:
    size: 5Gi

hcp-api:
  replicaCount: 1
  image:
    repository: hcp-api
    tag: latest
    pullPolicy: IfNotPresent
  credentialsSecret: hcp-credentials
  database:
    host: postgres
  env:
    HCP_PROVIDER: onprem
    HCP_ENV: dev
  parser:
    enabled: true
    image:
      repository: hcp-parser
      tag: latest
      pullPolicy: IfNotPresent
    queue: hcp.parse
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
